version: '3.8'
services:
  web:
    image: php:8.1-apache
    ports:
      - '8080:80'
    volumes:
      - ./backend:/var/www/html
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vanet_cms
    ports:
      - '3306:3306'
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
